name: 'Python project builder'
description: 'A sample custom GitHub Action written in Python'
inputs:
  python-version:
    description: "The python version to use"
    required: true

outputs:
  status_message:
    description: 'The final status message'

runs:
  using: 'composite'
  steps:
    - name: Welcome
      shell: bash
      run: |
        echo "I'm ${{ github.server_url }}/${{ github.repository }}"

    # https://github.com/actions/setup-python
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ inputs.python-version }}

    # https://github.com/astral-sh/setup-uv
    - name: Install uv
      uses: astral-sh/setup-uv@v9.0.0

    - name: Create venv
      shell: bash
      run: |
        uv sync --no-managed-python

    - name: Run Python Script
      shell: bash
      env:
        INPUT_USER_NAME: ${{ inputs.user_name }}
      run: python ${{ github.action_path }}/main.py

